"""
Extraction of cuticle regions using percentiles based on luminance intensity profiles 
obtained from transmission electron microscopy (TEM) images.

This script processes CSV files generated by ImageJ macros, in which
luminance intensity profiles are sampled at regular intervals along the X-axis 
on TEM images, perpendicular to the cell wall.

For each X position (sampling line), a threshold based on percentiles is applied
to identify low-intensity regions corresponding to the electron-dense cuticle layer.

Consecutive low-intensity regions are summarized by their upper boundary,
vertical extent (ROI height), and average intensity, and are output to a CSV file 
for each percentile threshold.

Required inputs:
  - CSV files containing columns: X, Y, Profile (luminance intensity)

Analysis parameters:
  - Percentile thresholds are predefined 
  - Stigma: Typically, the 3rd to 10th percentiles provide the best rendering
  - Style: A wider range (3rd to 25th percentiles) may be required
  - The final percentile threshold should be selected based on visual matching 
    with the continuous, electron-dense cuticle layer in each image.

Output:
  - CSV files containing:
      - Y_min: upper boundary (pixel)
      - ROI height: thickness (pixel)
      - Mean intensity
"""
import os
import pandas as pd
import numpy as np

# ===================== USER-DEFINED PARAMETERS =====================

# Input and output folder paths
input_folder = "/mnt/c/temp/pistil_profile_csv_250921"
output_folder = "/mnt/c/temp/pistil_black_line_csv_test260415"
os.makedirs(output_folder, exist_ok=True)

# Percentile thresholds used for cuticle detection
percentiles = [3, 5, 7, 10, 12, 14, 16, 18, 20, 25]

# ==================================================================


# -------- Load input files --------
csv_files = [f for f in os.listdir(input_folder) if f.endswith(".csv")]


# -------- Process each CSV file --------
for csv_file in csv_files:
    input_path = os.path.join(input_folder, csv_file)

    try:
        # Read CSV file and assign column names
        df = pd.read_csv(input_path, header=None)
        df.columns = ["Index", "X", "Y", "Profile"]

        # Ensure numeric intensity values
        df["Profile"] = pd.to_numeric(df["Profile"], errors='coerce')
        df = df.dropna(subset=["Profile"])

    except Exception as e:
        print(f"Error reading {csv_file}: {e}")
        continue


    # -------- Apply percentile-based thresholding --------
    for p in percentiles:

        results = []

        # Group by sampling position (X coordinate)
        for x_val, group in df.groupby("X"):

            profile_values = group["Profile"].values.astype(float)
            y_values = group["Y"].values.astype(float)

            # Compute percentile threshold
            threshold = np.percentile(profile_values, p)

            # Identify pixels below threshold (electron-dense region)
            below_threshold_indices = np.where(profile_values <= threshold)[0]

            if below_threshold_indices.size > 0:

                # Determine vertical extent of detected region
                y_min = y_values[below_threshold_indices].min()
                y_max = y_values[below_threshold_indices].max()
                roi_height = y_max - y_min + 1

                # Mean intensity within detected region
                mean_intensity = profile_values[below_threshold_indices].mean()

                results.append([x_val, y_min, roi_height, mean_intensity])


        # -------- Save results --------
        if results:
            output_df = pd.DataFrame(
                results,
                columns=["X", "Y_min (pixel)", "ROI_height (pixel)", "Mean_intensity"]
            )

            output_filename = f"{os.path.splitext(csv_file)[0]}_results_{p}percent.csv"
            output_path = os.path.join(output_folder, output_filename)

            output_df.to_csv(output_path, index=False)


print("Batch processing completed.")