/*
 * Reconstruction of percentile-based regions of interest (ROIs)
 * on transmission electron microscopy (TEM) image and  
 * quantitative measurement of cell wall and cuticle thickness.
 *
 * This macro reconstructs ROIs from CSV files generated by
 * percentile-based luminance profile analysis and quantitatively measures
 * ROI height and the distance from the bottom of the image.
 * ROI height corresponds to cuticle thickess, whereas the distance from the
 * bottom edge of the image represents cell wall thickness.
 * 
 * Recommended percentile ranges:
 *  - Stigma: 3–10th percentiles typically provide optimal cuticle delineation
 *  - Style: broader ranges (3–25th percentiles) may be required due to
 *          reduced contrast between the cell wall and cuticle
 * 
 * The final percentile threshold should be selected based on visual consistency
 * with the electron-dense cuticle layer in each image.
 * 
 * Required inputs:
 *  - Cropped TEM image (_crop.tif) obtained after straightening
 *    along the basal edge of the cell wall
 *  - CSV files containing y_min value and ROI height for each X-axis position
 *
 * Output:
 *  - TIFF images with reconstructed ROIs
 *  - CSV files containing quantitative measurement results
 */

// ===================== USER-DEFINED PARAMETERS =====================
inputImage  = "C:/temp/image9-23_crop.tif";          // Cropped TEM image
saveFolder  = "C:/temp/pistil_black_line_csv_250921/";
percentiles = newArray("3", "5", "7", "10", "12", "14", "16", "18", "20", "25");
// ==================================================================


// -------- Extract base names --------
imageFileName = File.getName(inputImage);
imageBase = replace(imageFileName, "_crop.tif", "");      // e.g. image12-1
csvBase   = replace(imageBase, "image", "pistil_profile_"); // e.g. pistil_profile_12-1


// -------- Main loop for each percentile --------
for (i = 0; i < percentiles.length; i++) {

    open(inputImage);
    roiManager("Reset");

    csvPath = saveFolder + "/" + csvBase + "_results_" + percentiles[i] + "percent.csv";
    if (!File.exists(csvPath)) {
        print("File not found: " + csvPath);
        close();
        continue;
    }

    table = File.openAsString(csvPath);
    lines = split(table, "\n");

    // Get pixel size for unit conversion
    getVoxelSize(pixelWidth, pixelHeight, pixelDepth, unit);

    for (j = 1; j < lines.length; j++) {

        if (lengthOf(lines[j]) == 0) continue;

        values = split(lines[j], ",");
        x      = parseInt(values[0]);
        y_min  = parseFloat(values[1]);
        height = parseFloat(values[2]);

        if (y_min < 0 || y_min + height > getHeight()) continue;

        // Create ROI
        makeRectangle(x, y_min, 1, height);
        roiManager("Add");
        roiManager("Select", roiManager("Count") - 1);
        roiManager("Rename", percentiles[i] + "percent_X" + x);
        roiManager("Measure");

        n = nResults();
        if (n == 0) continue;

        // Quantitative measurements
        getSelectionBounds(x1, y1, w1, h1);
        y_max = y1 + h1;
        imageHeight = getHeight();

        distanceFromBottom_um = (imageHeight - y_max) * pixelHeight;
        roiHeight_um          = h1 * pixelHeight;

        setResult("DistanceFromBottom_um", n - 1, distanceFromBottom_um);
        setResult("ROI_Height_um",          n - 1, roiHeight_um);
        updateResults();

        // Draw ROI on image
        run("Draw");
    }

    // Save quantitative results
    if (isOpen("Results")) {
        saveAs("Results",
               saveFolder + "/results_" + imageBase + "_" +
               percentiles[i] + "percent_measured.csv");
        close("Results");
    }

    // Save annotated image
    saveAs("Tiff",
           saveFolder + "/image_" + imageBase + "_" +
           percentiles[i] + "percent.tif");
    close();
}


// -------- Reopen all output images for visual inspection --------
for (i = 0; i < percentiles.length; i++) {
    open(saveFolder + "/image_" + imageBase + "_" +
         percentiles[i] + "percent.tif");
}